services:
  eksisozlukclone.api.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8080:8080
    # volumes:
      # - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - blazor_backend

  eksisozlukclone.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80  
    ports:
      - 80:80
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - blazor_frontend 

  c_postgres:
    container_name: c_postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - type: bind
        source: ./data/eksisozlukclone.sql
        target: /data/eksisozlukclone.sql      
    networks:
      - blazor_backend
    environment:
      POSTGRES_PASSWORD: "*sB2xa"
      POSTGRES_USER: postgres
      POSTGRES_DB: eksisozlukclone
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5433:5432
    

volumes:
  postgres_data:

networks:
  blazor_backend:
  blazor_frontend:
    